### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by jonapap** [carlosperate/arm-none-eabi-gcc-action#38]
We recently started getting this error while installing the latest tool chain.

```
...
| Cache miss, downloading GCC 12.2.Rel1 from https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz ; MD5 f3d1d32c8ac58f1e0f9dbe4bc56efa05
[Build/All]   💬  ::debug::Downloading https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz
[Build/All]   💬  ::debug::Destination /tmp/65f192c9-908f-4273-9e8e-96a85d5776ba
| unable to verify the first certificate
| Waiting 10 seconds before trying again
| unable to verify the first certificate
| Waiting 12 seconds before trying again
[Build/All]   ❗  ::error::unable to verify the first certificate
...
```

However, Firefox is able to access the website fine. Maybe this tool is only looking at the first certificate, and for some reason it is not valid right now?

**Comment by rserranosmith** [comment]
Having the same issue with `10.3-2021.07`. Must be a server issue

**Comment by mudge** [comment]
We're having the same problem on https://github.com/raspberrypi/documentation, it seems the certificate for developer.arm.com was renewed yesterday and it has a misconfigured chain according to https://whatsmychaincert.com/?developer.arm.com

For now, we can work around this by disabling Node.js' SSL verification but this is obviously insecure and not ideal, e.g.

```yaml
      - name: Install arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.6.0
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
```

(See also https://github.com/raspberrypi/documentation/pull/2909/commits/695a91f46935735379337dd8d02aa29903808d78)
